### ISSUE TITLE
Failed to resolve Nowin.vNext

### ISSUE THREAD

**Issue by tobizahner** [cloudfoundry-community/asp.net5-buildpack#6]
I tried to use the buildpack on our cf platform but had no success. Build and upload works but than the app crashes / can not start. So i looked into the log file and got the following error:

OUT Starting app instance (index 0) with guid [...]
OUT     Adding /app/.k/runtimes/kre-mono.1.0.0-beta3/bin to process PATH
ERR System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'Asp.Net,Version=v5.0':
ERR    Nowin.vNext 1.0.0
ERR Searched Locations:
ERR   /home/vcap/app/approot/src/{name}/project.json
ERR   /home/vcap/app/approot/test/{name}/project.json
ERR   /home/vcap/app/approot/packages/{name}/{version}/{name}.nuspec
ERR   /home/vcap/app/mono/lib/mono/4.5/{name}.dll
ERR   /home/vcap/app/mono/lib/mono/4.5/Facades/{name}.dll

Any Ideas what could be the problem? File structure should be correct as I tested it also with the Hello World samle --> no success.

**Comment by opiethehokie** [comment]
When you try the Hello World sample, what directory are you pushing from? It should be the root directory which contains the NuGet.config file.

**Comment by opiethehokie** [comment]
This wouldn't have explained why the Hello World sample didn't work, but I think the error could also have been caused by the app specifying just the aspnetcore50 framework in project.json because the buildpack would be trying to use the full CLR.

**Comment by drungrin** [comment]
If your error is similar to mine,
OUT Error: FindPackagesById: Nowin.vNext
OUT   Error: SendFailure (Error writing headers)

It is because you are pushing from the project dir instead of the "solution" dir (the one that contains the NuGet.config file. The same error occurs with the dotnetstarter from bluemix.

Another thing to note is that if your project.json specify the dependencies as "1.0.0-*" means that it 'll use the latest version, which is the beta5 one. The build pack is for beta4.

@opiethehokie I think you could provide a hello world also.

**Comment by opiethehokie** [comment]
The hello world linked in the README is updated for beta4 now. It's the same as the Bluemix one but doesn't require using Bluemix in any way.
